name: "Run scraper"
on:
  schedule:
  - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: sudo apt purge google-chrome-stable
      - run: sudo apt purge chromium-browser
      - run: sudo apt install -y chromium-browser
      - run: pip install selenium==3.141 numpy pandas trueskill hopsworks tensorflow
      - run: python feature-upcoming-pipeline.py
